CREATE schema one_to_one_v2;

create table one_to_one_v2.person
(
    id   int primary key generated by default as identity,
    name varchar(100) not null,
    age  int
);

create table one_to_one_v2.passport
(
    id              int primary key generated by default as identity,
    person_id       int unique references one_to_one_v2.person (id) on delete cascade,--первичный и внешний ключ
    passport_number int not null
);